BlogBundle\Entity\Rubric:
    type: entity
    table: rubric
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        authorId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: author_id
        rubric:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        posts:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
