BlogBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nickname:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        passwd:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        about:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
            default: ''
        cdate:
            type: date
            nullable: false
            comment: ''
        posts:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
